//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zi.SalesModule.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en-US")]
        public string CultureName {
            get {
                return ((string)(this["CultureName"]));
            }
            set {
                this["CultureName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gainsboro")]
        public global::System.Drawing.Color BaseTextColor {
            get {
                return ((global::System.Drawing.Color)(this["BaseTextColor"]));
            }
            set {
                this["BaseTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("79, 202, 178")]
        public global::System.Drawing.Color BaseIconColor {
            get {
                return ((global::System.Drawing.Color)(this["BaseIconColor"]));
            }
            set {
                this["BaseIconColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("79, 202, 178")]
        public global::System.Drawing.Color BaseBorderColor {
            get {
                return ((global::System.Drawing.Color)(this["BaseBorderColor"]));
            }
            set {
                this["BaseBorderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4, 119, 250")]
        public global::System.Drawing.Color BaseHoverColor {
            get {
                return ((global::System.Drawing.Color)(this["BaseHoverColor"]));
            }
            set {
                this["BaseHoverColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowSayBye {
            get {
                return ((bool)(this["AllowSayBye"]));
            }
            set {
                this["AllowSayBye"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int VoiceBotVolumn {
            get {
                return ((int)(this["VoiceBotVolumn"]));
            }
            set {
                this["VoiceBotVolumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VoiceBotSpeakerRate {
            get {
                return ((int)(this["VoiceBotSpeakerRate"]));
            }
            set {
                this["VoiceBotSpeakerRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowInitSound {
            get {
                return ((bool)(this["AllowInitSound"]));
            }
            set {
                this["AllowInitSound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowClickSound {
            get {
                return ((bool)(this["AllowClickSound"]));
            }
            set {
                this["AllowClickSound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color ErrorTextColor {
            get {
                return ((global::System.Drawing.Color)(this["ErrorTextColor"]));
            }
            set {
                this["ErrorTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 192, 0")]
        public global::System.Drawing.Color SuccessTextColor {
            get {
                return ((global::System.Drawing.Color)(this["SuccessTextColor"]));
            }
            set {
                this["SuccessTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 128, 0")]
        public global::System.Drawing.Color WarningTextColor {
            get {
                return ((global::System.Drawing.Color)(this["WarningTextColor"]));
            }
            set {
                this["WarningTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aqua")]
        public global::System.Drawing.Color InfoTextColor {
            get {
                return ((global::System.Drawing.Color)(this["InfoTextColor"]));
            }
            set {
                this["InfoTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("46, 61, 74")]
        public global::System.Drawing.Color HeaderBackColor {
            get {
                return ((global::System.Drawing.Color)(this["HeaderBackColor"]));
            }
            set {
                this["HeaderBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("46, 61, 74")]
        public global::System.Drawing.Color FooterBackColor {
            get {
                return ((global::System.Drawing.Color)(this["FooterBackColor"]));
            }
            set {
                this["FooterBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("46, 61, 74")]
        public global::System.Drawing.Color LeftSideBarBackColor {
            get {
                return ((global::System.Drawing.Color)(this["LeftSideBarBackColor"]));
            }
            set {
                this["LeftSideBarBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("46, 61, 74")]
        public global::System.Drawing.Color RightSideBarBackColor {
            get {
                return ((global::System.Drawing.Color)(this["RightSideBarBackColor"]));
            }
            set {
                this["RightSideBarBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("38, 49, 61")]
        public global::System.Drawing.Color BodyBackColor {
            get {
                return ((global::System.Drawing.Color)(this["BodyBackColor"]));
            }
            set {
                this["BodyBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color BlurTextColor {
            get {
                return ((global::System.Drawing.Color)(this["BlurTextColor"]));
            }
            set {
                this["BlurTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowSoundtrack {
            get {
                return ((bool)(this["AllowSoundtrack"]));
            }
            set {
                this["AllowSoundtrack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LangQuenChieuThuSoundtrack.wav")]
        public string SoundtrackFileName {
            get {
                return ((string)(this["SoundtrackFileName"]));
            }
            set {
                this["SoundtrackFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.facebook.com/ZI.TECH.DEV.201")]
        public string DeveloperFacebookLink {
            get {
                return ((string)(this["DeveloperFacebookLink"]));
            }
            set {
                this["DeveloperFacebookLink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mailto:zitech.dev[at]gmail.com?subject=Customer Feedback&bcc=sotayvaodoi[at]gmail" +
            ".com")]
        public string DeveloperMailToCmd {
            get {
                return ((string)(this["DeveloperMailToCmd"]));
            }
            set {
                this["DeveloperMailToCmd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200, 200")]
        public global::System.Drawing.Size TableItemSize {
            get {
                return ((global::System.Drawing.Size)(this["TableItemSize"]));
            }
            set {
                this["TableItemSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200, 50")]
        public global::System.Drawing.Size AreaItemSize {
            get {
                return ((global::System.Drawing.Size)(this["AreaItemSize"]));
            }
            set {
                this["AreaItemSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400, 200")]
        public global::System.Drawing.Size HorizontalProductItemSize {
            get {
                return ((global::System.Drawing.Size)(this["HorizontalProductItemSize"]));
            }
            set {
                this["HorizontalProductItemSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int DropShadowDepth {
            get {
                return ((int)(this["DropShadowDepth"]));
            }
            set {
                this["DropShadowDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("28, 39, 49")]
        public global::System.Drawing.Color BaseItemColor {
            get {
                return ((global::System.Drawing.Color)(this["BaseItemColor"]));
            }
            set {
                this["BaseItemColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("34, 46, 58")]
        public global::System.Drawing.Color DropShadowColor {
            get {
                return ((global::System.Drawing.Color)(this["DropShadowColor"]));
            }
            set {
                this["DropShadowColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int CornerRadius {
            get {
                return ((int)(this["CornerRadius"]));
            }
            set {
                this["CornerRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23, 42, 70")]
        public global::System.Drawing.Color MsgBackColor {
            get {
                return ((global::System.Drawing.Color)(this["MsgBackColor"]));
            }
            set {
                this["MsgBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int AlertTimer {
            get {
                return ((int)(this["AlertTimer"]));
            }
            set {
                this["AlertTimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("46, 61, 74")]
        public global::System.Drawing.Color BaseBackColor {
            get {
                return ((global::System.Drawing.Color)(this["BaseBackColor"]));
            }
            set {
                this["BaseBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300, 50")]
        public global::System.Drawing.Size CategoryItemSize {
            get {
                return ((global::System.Drawing.Size)(this["CategoryItemSize"]));
            }
            set {
                this["CategoryItemSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200, 400")]
        public global::System.Drawing.Size VerticalProductItemSize {
            get {
                return ((global::System.Drawing.Size)(this["VerticalProductItemSize"]));
            }
            set {
                this["VerticalProductItemSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4, 119, 250")]
        public global::System.Drawing.Color ItemSelectedColor {
            get {
                return ((global::System.Drawing.Color)(this["ItemSelectedColor"]));
            }
            set {
                this["ItemSelectedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("33, 46, 58")]
        public global::System.Drawing.Color ItemHoverColor {
            get {
                return ((global::System.Drawing.Color)(this["ItemHoverColor"]));
            }
            set {
                this["ItemHoverColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public float DefaultTax {
            get {
                return ((float)(this["DefaultTax"]));
            }
            set {
                this["DefaultTax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowScanDetectedSound {
            get {
                return ((bool)(this["AllowScanDetectedSound"]));
            }
            set {
                this["AllowScanDetectedSound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int RoundingTo {
            get {
                return ((int)(this["RoundingTo"]));
            }
            set {
                this["RoundingTo"] = value;
            }
        }
    }
}
