//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zi.SalesModule.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en-US")]
        public string CultureName {
            get {
                return ((string)(this["CultureName"]));
            }
            set {
                this["CultureName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gainsboro")]
        public global::System.Drawing.Color BaseTextColor {
            get {
                return ((global::System.Drawing.Color)(this["BaseTextColor"]));
            }
            set {
                this["BaseTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("79, 202, 178")]
        public global::System.Drawing.Color BaseIconColor {
            get {
                return ((global::System.Drawing.Color)(this["BaseIconColor"]));
            }
            set {
                this["BaseIconColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("79, 202, 178")]
        public global::System.Drawing.Color BaseBorderColor {
            get {
                return ((global::System.Drawing.Color)(this["BaseBorderColor"]));
            }
            set {
                this["BaseBorderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4, 119, 250")]
        public global::System.Drawing.Color BaseHoverColor {
            get {
                return ((global::System.Drawing.Color)(this["BaseHoverColor"]));
            }
            set {
                this["BaseHoverColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowSayBye {
            get {
                return ((bool)(this["AllowSayBye"]));
            }
            set {
                this["AllowSayBye"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int VoiceBotVolumn {
            get {
                return ((int)(this["VoiceBotVolumn"]));
            }
            set {
                this["VoiceBotVolumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VoiceBotSpeakerRate {
            get {
                return ((int)(this["VoiceBotSpeakerRate"]));
            }
            set {
                this["VoiceBotSpeakerRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowInitSound {
            get {
                return ((bool)(this["AllowInitSound"]));
            }
            set {
                this["AllowInitSound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowClickSound {
            get {
                return ((bool)(this["AllowClickSound"]));
            }
            set {
                this["AllowClickSound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color ErrorTextColor {
            get {
                return ((global::System.Drawing.Color)(this["ErrorTextColor"]));
            }
            set {
                this["ErrorTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 192, 0")]
        public global::System.Drawing.Color SuccessTextColor {
            get {
                return ((global::System.Drawing.Color)(this["SuccessTextColor"]));
            }
            set {
                this["SuccessTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 128, 0")]
        public global::System.Drawing.Color WarningTextColor {
            get {
                return ((global::System.Drawing.Color)(this["WarningTextColor"]));
            }
            set {
                this["WarningTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aqua")]
        public global::System.Drawing.Color InfoTextColor {
            get {
                return ((global::System.Drawing.Color)(this["InfoTextColor"]));
            }
            set {
                this["InfoTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("46, 61, 74")]
        public global::System.Drawing.Color HeaderBackColor {
            get {
                return ((global::System.Drawing.Color)(this["HeaderBackColor"]));
            }
            set {
                this["HeaderBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("46, 61, 74")]
        public global::System.Drawing.Color FooterBackColor {
            get {
                return ((global::System.Drawing.Color)(this["FooterBackColor"]));
            }
            set {
                this["FooterBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("46, 61, 74")]
        public global::System.Drawing.Color LeftSideBarBackColor {
            get {
                return ((global::System.Drawing.Color)(this["LeftSideBarBackColor"]));
            }
            set {
                this["LeftSideBarBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("46, 61, 74")]
        public global::System.Drawing.Color RightSideBarBackColor {
            get {
                return ((global::System.Drawing.Color)(this["RightSideBarBackColor"]));
            }
            set {
                this["RightSideBarBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("38, 49, 61")]
        public global::System.Drawing.Color BodyBackColor {
            get {
                return ((global::System.Drawing.Color)(this["BodyBackColor"]));
            }
            set {
                this["BodyBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color BlurTextColor {
            get {
                return ((global::System.Drawing.Color)(this["BlurTextColor"]));
            }
            set {
                this["BlurTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowSoundtrack {
            get {
                return ((bool)(this["AllowSoundtrack"]));
            }
            set {
                this["AllowSoundtrack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LangQuenChieuThuSoundtrack.wav")]
        public string SoundtrackFileName {
            get {
                return ((string)(this["SoundtrackFileName"]));
            }
            set {
                this["SoundtrackFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>2512015c-b463-4fe1-8fd2-c2c33434a6d9</string>
  <string>111958c7-e6d6-4278-8eb7-e17cc7fd8af5</string>
  <string>353692cb-e5dc-4ca3-af81-3f64b019650b</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ManagerRoleId {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ManagerRoleId"]));
            }
            set {
                this["ManagerRoleId"] = value;
            }
        }
    }
}
