//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zi.ZiCoffee.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\sqlexpress;Initial Catalog=QLCF;Integrated Security=True")]
        public string QLCFConnectionString {
            get {
                return ((string)(this["QLCFConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsGreeting {
            get {
                return ((bool)(this["IsGreeting"]));
            }
            set {
                this["IsGreeting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsBye {
            get {
                return ((bool)(this["IsBye"]));
            }
            set {
                this["IsBye"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsSoundTrack {
            get {
                return ((bool)(this["IsSoundTrack"]));
            }
            set {
                this["IsSoundTrack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsClick {
            get {
                return ((bool)(this["IsClick"]));
            }
            set {
                this["IsClick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsAppearance {
            get {
                return ((bool)(this["IsAppearance"]));
            }
            set {
                this["IsAppearance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsNotification {
            get {
                return ((bool)(this["IsNotification"]));
            }
            set {
                this["IsNotification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ZiTechDev Chuyên cung cấp các giải pháp và phát triển phần mềm.")]
        public string companyIntroduce {
            get {
                return ((string)(this["companyIntroduce"]));
            }
            set {
                this["companyIntroduce"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21Bis Điện Biên Phủ - Phường 25 - Quận Bình Thạnh - Thành phố Hồ Chí Minh - Việt " +
            "Nam")]
        public string companyAddress {
            get {
                return ((string)(this["companyAddress"]));
            }
            set {
                this["companyAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21Bis Điện Biên Phủ - Phường 25")]
        public string companyAddressBill1 {
            get {
                return ((string)(this["companyAddressBill1"]));
            }
            set {
                this["companyAddressBill1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(+84) 943 144 178")]
        public string companyPhone1 {
            get {
                return ((string)(this["companyPhone1"]));
            }
            set {
                this["companyPhone1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(+84) 382 663 470")]
        public string companyPhone2 {
            get {
                return ((string)(this["companyPhone2"]));
            }
            set {
                this["companyPhone2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("zitech.dev@gmail.com")]
        public string companyEmail1 {
            get {
                return ((string)(this["companyEmail1"]));
            }
            set {
                this["companyEmail1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sotayvaodoi@gmail.com")]
        public string companyEmail2 {
            get {
                return ((string)(this["companyEmail2"]));
            }
            set {
                this["companyEmail2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7410 852 9630 000 - Nguyễn Ngọc Hiếu - Chi nhánh TechComBank Bình Thạnh")]
        public string companyBank1 {
            get {
                return ((string)(this["companyBank1"]));
            }
            set {
                this["companyBank1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string companyBank2 {
            get {
                return ((string)(this["companyBank2"]));
            }
            set {
                this["companyBank2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.facebook.com/zitech.dev/")]
        public string linkFacebook {
            get {
                return ((string)(this["linkFacebook"]));
            }
            set {
                this["linkFacebook"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.youtube.com/channel/UCwmKzLFHfs79flAnrHRptdA")]
        public string linkYoutube {
            get {
                return ((string)(this["linkYoutube"]));
            }
            set {
                this["linkYoutube"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://zitechdev.com/")]
        public string linkWebsite {
            get {
                return ((string)(this["linkWebsite"]));
            }
            set {
                this["linkWebsite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string linkInstagram {
            get {
                return ((string)(this["linkInstagram"]));
            }
            set {
                this["linkInstagram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string linkGooglePlus {
            get {
                return ((string)(this["linkGooglePlus"]));
            }
            set {
                this["linkGooglePlus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ipAdress {
            get {
                return ((string)(this["ipAdress"]));
            }
            set {
                this["ipAdress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("163")]
        public int ServiceItemWidth {
            get {
                return ((int)(this["ServiceItemWidth"]));
            }
            set {
                this["ServiceItemWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("210")]
        public int ServiceItemHeigh {
            get {
                return ((int)(this["ServiceItemHeigh"]));
            }
            set {
                this["ServiceItemHeigh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("133")]
        public int TableItemWidth {
            get {
                return ((int)(this["TableItemWidth"]));
            }
            set {
                this["TableItemWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("133")]
        public int TableItemHeigh {
            get {
                return ((int)(this["TableItemHeigh"]));
            }
            set {
                this["TableItemHeigh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int SpeakerVolumn {
            get {
                return ((int)(this["SpeakerVolumn"]));
            }
            set {
                this["SpeakerVolumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SpeakerRate {
            get {
                return ((int)(this["SpeakerRate"]));
            }
            set {
                this["SpeakerRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Goodbye, See you later!")]
        public string Goodbye {
            get {
                return ((string)(this["Goodbye"]));
            }
            set {
                this["Goodbye"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"Welcome to Coffee Shop Managerment. How are you ,today?\"")]
        public string Welcome {
            get {
                return ((string)(this["Welcome"]));
            }
            set {
                this["Welcome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Q.Bình Thạnh - TP.HCM - Việt Nam")]
        public string companyAddressBill2 {
            get {
                return ((string)(this["companyAddressBill2"]));
            }
            set {
                this["companyAddressBill2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VND")]
        public string currencySymbol {
            get {
                return ((string)(this["currencySymbol"]));
            }
            set {
                this["currencySymbol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("vi-VN")]
        public string CultureName {
            get {
                return ((string)(this["CultureName"]));
            }
            set {
                this["CultureName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color MainBack {
            get {
                return ((global::System.Drawing.Color)(this["MainBack"]));
            }
            set {
                this["MainBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color HFBack {
            get {
                return ((global::System.Drawing.Color)(this["HFBack"]));
            }
            set {
                this["HFBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color PopupBack {
            get {
                return ((global::System.Drawing.Color)(this["PopupBack"]));
            }
            set {
                this["PopupBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ContentBack {
            get {
                return ((global::System.Drawing.Color)(this["ContentBack"]));
            }
            set {
                this["ContentBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ButtonBackNoBorder {
            get {
                return ((global::System.Drawing.Color)(this["ButtonBackNoBorder"]));
            }
            set {
                this["ButtonBackNoBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color DisabledBack {
            get {
                return ((global::System.Drawing.Color)(this["DisabledBack"]));
            }
            set {
                this["DisabledBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color MainFore {
            get {
                return ((global::System.Drawing.Color)(this["MainFore"]));
            }
            set {
                this["MainFore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color HFFore {
            get {
                return ((global::System.Drawing.Color)(this["HFFore"]));
            }
            set {
                this["HFFore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color PopupFore {
            get {
                return ((global::System.Drawing.Color)(this["PopupFore"]));
            }
            set {
                this["PopupFore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ContentFore {
            get {
                return ((global::System.Drawing.Color)(this["ContentFore"]));
            }
            set {
                this["ContentFore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ButtonForeNoBorder {
            get {
                return ((global::System.Drawing.Color)(this["ButtonForeNoBorder"]));
            }
            set {
                this["ButtonForeNoBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color SuccessFore {
            get {
                return ((global::System.Drawing.Color)(this["SuccessFore"]));
            }
            set {
                this["SuccessFore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ErrorFore {
            get {
                return ((global::System.Drawing.Color)(this["ErrorFore"]));
            }
            set {
                this["ErrorFore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color WarningFore {
            get {
                return ((global::System.Drawing.Color)(this["WarningFore"]));
            }
            set {
                this["WarningFore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsDarkTheme {
            get {
                return ((bool)(this["IsDarkTheme"]));
            }
            set {
                this["IsDarkTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color MinimizeBack {
            get {
                return ((global::System.Drawing.Color)(this["MinimizeBack"]));
            }
            set {
                this["MinimizeBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color MaximizeBack {
            get {
                return ((global::System.Drawing.Color)(this["MaximizeBack"]));
            }
            set {
                this["MaximizeBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color CloseBack {
            get {
                return ((global::System.Drawing.Color)(this["CloseBack"]));
            }
            set {
                this["CloseBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsLightTheme {
            get {
                return ((bool)(this["IsLightTheme"]));
            }
            set {
                this["IsLightTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ButtonBackBorder {
            get {
                return ((global::System.Drawing.Color)(this["ButtonBackBorder"]));
            }
            set {
                this["ButtonBackBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ButtonForeBorder {
            get {
                return ((global::System.Drawing.Color)(this["ButtonForeBorder"]));
            }
            set {
                this["ButtonForeBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color WinStateBack {
            get {
                return ((global::System.Drawing.Color)(this["WinStateBack"]));
            }
            set {
                this["WinStateBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color HighlightEffectBack {
            get {
                return ((global::System.Drawing.Color)(this["HighlightEffectBack"]));
            }
            set {
                this["HighlightEffectBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color DisabledFore {
            get {
                return ((global::System.Drawing.Color)(this["DisabledFore"]));
            }
            set {
                this["DisabledFore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ButtonBackNavHover {
            get {
                return ((global::System.Drawing.Color)(this["ButtonBackNavHover"]));
            }
            set {
                this["ButtonBackNavHover"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ButtonBackBlueHover {
            get {
                return ((global::System.Drawing.Color)(this["ButtonBackBlueHover"]));
            }
            set {
                this["ButtonBackBlueHover"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 168, 255")]
        public global::System.Drawing.Color TableItemTempBack {
            get {
                return ((global::System.Drawing.Color)(this["TableItemTempBack"]));
            }
            set {
                this["TableItemTempBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color TableItemFore {
            get {
                return ((global::System.Drawing.Color)(this["TableItemFore"]));
            }
            set {
                this["TableItemFore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color ServiceItemEnabledBack {
            get {
                return ((global::System.Drawing.Color)(this["ServiceItemEnabledBack"]));
            }
            set {
                this["ServiceItemEnabledBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color ServiceItemNameFore {
            get {
                return ((global::System.Drawing.Color)(this["ServiceItemNameFore"]));
            }
            set {
                this["ServiceItemNameFore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public global::System.Drawing.Color TableItemUsingBack {
            get {
                return ((global::System.Drawing.Color)(this["TableItemUsingBack"]));
            }
            set {
                this["TableItemUsingBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color ServiceItemDisabledBack {
            get {
                return ((global::System.Drawing.Color)(this["ServiceItemDisabledBack"]));
            }
            set {
                this["ServiceItemDisabledBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color ServiceItemPriceFore {
            get {
                return ((global::System.Drawing.Color)(this["ServiceItemPriceFore"]));
            }
            set {
                this["ServiceItemPriceFore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SplashId {
            get {
                return ((int)(this["SplashId"]));
            }
            set {
                this["SplashId"] = value;
            }
        }
    }
}
